[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# remappings=["@openzeppelin=node_modules/openzeppelin/contracts"]
remappings=[
    "@solmate=lib/solmate/",
    "@openzeppelin=lib/openzeppelin-contracts/contracts",
]
# "@openzeppelin/contracts/access/Ownable.sol";
# import {IAToken} from "@aave/core-v3/contracts/interfaces/IAToken.sol";

# remappings = ["@chainlink=lib/chainlink-brownie-contracts/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
